<?xml version="1.0"?>
<package format="3">
  <name>d1_description</name>
  <version>3.0.0</version>
  <description>D1 robot description package</description>
  <maintainer email="fanziqi614@gmail.com">Ziqi Fan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_state_publisher</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>

  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
