/*
* Copyright (c) 2024-2025 Ziqi Fan
* SPDX-License-Identifier: Apache-2.0
*/
#include "rl_real_d1.hpp"
#include "command_shaping.hpp"

#include <algorithm>
#include <cmath>

#if defined(USE_ROS1)
    #include "std_msgs/Float64MultiArray.h"
#elif defined(USE_ROS2)
    #include <std_msgs/msg/float64_multi_array.hpp>
#endif

// Construct the real-robot D1 controller.
//
// This performs the main real-robot node initialization: create ROS topics, read base.yaml, create the state machine,
// open CAN buses, and start periodic loops for keyboard, gamepad, control, and RL inference.
// Specific motion logic is generated by the FSM and RL modules in their own cycles.
RL_Real::RL_Real(int argc, char **argv)
{
#if defined(USE_ROS1)
    ros::NodeHandle nh;
    // /cmd_vel caches external velocity commands; whether they are used depends on the current control mode.
    this->cmd_vel_subscriber = nh.subscribe<geometry_msgs::Twist>("/cmd_vel", 10, &RL_Real::CmdvelCallback, this);
    // The IMU callback only caches the latest orientation and angular velocity. Data actually used by the controller
    // is copied from the cached message by GetState() in each control cycle.
    this->odom_sub_ = nh.subscribe("/imu/data", 1, &RL_Real::OdomCallBack, this);
    joint_state_pub_ = nh.advertise<sensor_msgs::JointState>("/joint_states", 10);
#elif defined(USE_ROS2)
    ros2_node = std::make_shared<rclcpp::Node>("rl_real_node");
    // /cmd_vel caches external velocity commands; whether they are used depends on the current control mode.
    cmd_vel_subscriber = ros2_node->create_subscription<geometry_msgs::msg::Twist>(
        "/cmd_vel", rclcpp::SystemDefaultsQoS(),
        std::bind(&RL_Real::CmdvelCallback, this, std::placeholders::_1));
    // The IMU callback only caches the latest orientation and angular velocity. Data actually used by the controller
    // is copied from the cached message by GetState() in each control cycle.
    odom_sub_ = ros2_node->create_subscription<sensor_msgs::msg::Imu>(
        "/imu/data", 10,
        std::bind(&RL_Real::OdomCallBack, this, std::placeholders::_1));
    joint_state_pub_ = ros2_node->create_publisher<sensor_msgs::msg::JointState>(
        "/joint_states", 10);
    dog_usb_enable = ros2_node->declare_parameter<bool>("dog_usb_enable", false);
    dog_usb_device = ros2_node->declare_parameter<std::string>("dog_usb_device", "");
    dog_usb_baud = ros2_node->declare_parameter<int>("dog_usb_baud", 115200);
    dog_usb_timeout_ms = ros2_node->declare_parameter<int>("dog_usb_timeout_ms", 300);
    dog_remote_timeout_ms = ros2_node->declare_parameter<int>("dog_remote_timeout_ms", 1500);
    dog_usb_allow_fallback = ros2_node->declare_parameter<bool>("dog_usb_allow_fallback", false);
    dog_usb_l1_off_exit = ros2_node->declare_parameter<bool>("dog_usb_l1_off_exit", false);
    dog_usb_l1_button_bit = ros2_node->declare_parameter<int>("dog_usb_l1_button_bit", 8);
    dog_usb_l1_exit_timeout_ms = ros2_node->declare_parameter<int>("dog_usb_l1_exit_timeout_ms", 8000);
    keyboard_enable = ros2_node->declare_parameter<bool>("keyboard_enable", true);
    sys_joystick_device = ros2_node->declare_parameter<std::string>("sys_joystick_device", "/dev/input/js0");
    if (dog_usb_timeout_ms < 1) {dog_usb_timeout_ms = 300;}
    if (dog_remote_timeout_ms < 1) {dog_remote_timeout_ms = 1500;}
    if (dog_usb_l1_button_bit < 0 || dog_usb_l1_button_bit > 15) {dog_usb_l1_button_bit = 8;}
    if (dog_usb_l1_exit_timeout_ms < 1) {dog_usb_l1_exit_timeout_ms = 8000;}
    if (this->dog_usb_enable)
    {
        if (this->dog_usb_device.empty())
        {
            std::cout << LOGGER::ERROR
                      << "[dog_usb] dog_usb_enable=true but dog_usb_device is empty; not starting dog USB receiver."
                      << std::endl;
        }
        else
        {
            this->dog_usb_receiver = std::make_unique<DogUsbReceiver>();
            if (!this->dog_usb_receiver->Start(this->dog_usb_device, this->dog_usb_baud))
            {
                std::cout << LOGGER::ERROR << "[dog_usb] receiver start failed for "
                          << this->dog_usb_device << std::endl;
                this->dog_usb_receiver.reset();
            }
        }
    }
#endif
    // Linux joystick devices produce button and stick events. GetSysJoystick() converts raw events
    // into unified Input::Gamepad control inputs for FSM and policy control.
    this->SetupSysJoystick(this->sys_joystick_device, 16); //  ls -l /dev/input/js*

    // Before creating the state machine and control loops, read the D1 base config. base.yaml provides control
    // period, fixed gains, DoF count, joint names, default joint positions, and other common parameters.
    this->ang_vel_axis = "body";
    this->robot_name = "d1";
    this->ReadYaml(this->robot_name, "base.yaml");//base.yaml

    // Create the robot-specific state machine from robot_name. In each later control cycle, the FSM
    // generates the corresponding RobotCommand from the current state and inputs.
    if (FSMManager::GetInstance().IsTypeSupported(this->robot_name))
    {
        auto fsm_ptr = FSMManager::GetInstance().CreateFSM(this->robot_name, this);
        if (fsm_ptr)
        {
            this->fsm = *fsm_ptr;
        }
    }
    else
    {
        std::cout << LOGGER::ERROR << "[FSM] No FSM registered for robot: " << this->robot_name << std::endl;
    }

    // Allocate state, command, and observation buffers according to the DoF count in base.yaml. The joint order here
    // must stay consistent with joint_names, joint_mapping, and default_dof_pos.
    this->InitJointNum(this->params.Get<int>("num_of_dofs"));
    this->InitOutputs();
    this->InitControl();
    this->setupImu();
    int num_of_dofs = this->params.Get<int>("num_of_dofs");
    this->joint_mapping = this->params.Get<std::vector<int>>("joint_mapping");
    this->joint_names_ = this->params.Get<std::vector<std::string>>("joint_names");
    
    // The current real-robot branch assumes CAN1 is the first group of 6 motors. Motor ids 1..6 are expected to map in order to:
    // FL_hip, FL_thigh, FL_calf, FR_hip, FR_thigh, FR_calf.
    // Physical wiring, motor ids, and the order here must match.
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x01,.mst_id=0x11});
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x02,.mst_id=0x12});
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x03,.mst_id=0x13});
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x04,.mst_id=0x14});
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x05,.mst_id=0x15});
    this->CAN1.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x06,.mst_id=0x16});

    // CAN2 is the second group of 6 motors. CAN2 also uses motor ids 1..6, but it and CAN1
    // are different SocketCAN devices, so the same id maps to another physical motor group.
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x01,.mst_id=0x11});
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x02,.mst_id=0x12});
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x03,.mst_id=0x13});
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x04,.mst_id=0x14});
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x05,.mst_id=0x15});
    this->CAN2.push_back(damiao::DmActData{.motorType = damiao::DM6248P,.mode = damiao::MIT_MODE,.can_id=0x06,.mst_id=0x16});
    
    // Motor_Control opens SocketCAN and maintains TX/RX state for all motors on that bus.
    // This branch follows the Jetson real-robot deployment and uses can1/can2 instead of can0/can1.
    this->motorsInterface = std::make_shared<damiao::Motor_Control>("can1",&this->CAN1,damiao::canfd);
    this->motorsInterface2 = std::make_shared<damiao::Motor_Control>("can2",&this->CAN2,damiao::canfd);

    // Do not write zero positions automatically in the main control node. Zero calibration is a separate, risky hardware operation
    // that should use set_zero_all or set_zero_one after suspending the robot and confirming the pose.
    // for (int i = 1; i < 7; ++i) {
    // this->motorsInterface->set_zero_position(*this->motorsInterface->getMotor(i));
    // }
    // for (int i = 1; i < 7; ++i) {
    // this->motorsInterface2->set_zero_position(*this->motorsInterface2->getMotor(i));
    // }

    // Start periodic threads. loop_control is the real motor closed-loop control thread; in base.yaml,
    // dt=0.005 makes RobotControl() run at 200 Hz.
    this->loop_control = std::make_shared<LoopFunc>("loop_control", this->params.Get<float>("dt"), std::bind(&RL_Real::RobotControl, this));
    // loop_rl only produces policy outputs when rl_init_done is true; whether it is set is decided by the FSM
    // state-specific logic.
    this->loop_rl = std::make_shared<LoopFunc>("loop_rl", this->params.Get<float>("dt") * this->params.Get<int>("decimation"), std::bind(&RL_Real::RunModel, this));
    if (this->keyboard_enable)
    {
        this->loop_keyboard = std::make_shared<LoopFunc>("loop_keyboard", 0.05, std::bind(&RL_Real::KeyboardInterface, this));
        this->loop_keyboard->start();
    }
    else
    {
        std::cout << LOGGER::INFO << "Keyboard input disabled by parameter keyboard_enable=false" << std::endl;
    }
    this->loop_control->start();
    this->loop_rl->start();

    // Gamepad polling runs faster than the main control rate so short button presses are not missed by the control thread.
    this->loop_joystick = std::make_shared<LoopFunc>("loop_joystick", 0.01, std::bind(&RL_Real::GetSysJoystick, this));
    this->loop_joystick->start();
#ifdef PLOT
    this->plot_t = std::vector<int>(this->plot_size, 0);
    this->plot_real_joint_pos.resize(this->params.Get<int>("num_of_dofs"));
    this->plot_target_joint_pos.resize(this->params.Get<int>("num_of_dofs"));
    for (auto &vector : this->plot_real_joint_pos) { vector = std::vector<float>(this->plot_size, 0); }
    for (auto &vector : this->plot_target_joint_pos) { vector = std::vector<float>(this->plot_size, 0); }
    this->loop_plot = std::make_shared<LoopFunc>("loop_plot", 0.002, std::bind(&RL_Real::Plot, this));
    this->loop_plot->start();
#endif
#ifdef CSV_LOGGER
    this->CSVInit(this->robot_name);
#endif
}

RL_Real::~RL_Real()
{
    if (this->loop_keyboard) {this->loop_keyboard->shutdown();}
    if (this->loop_control) {this->loop_control->shutdown();}
    if (this->loop_rl) {this->loop_rl->shutdown();}
    if (this->loop_joystick) {this->loop_joystick->shutdown();}
    if (this->dog_usb_receiver)
    {
        this->dog_usb_receiver->Stop();
    }
#ifdef PLOT
    this->loop_plot->shutdown();
#endif
    std::cout << LOGGER::INFO << "RL_Real exit------!!!!!!!!!" << std::endl;
}

// Copy the latest hardware state into the controller state structure.
//
// The state machine and policy network use the model joint order defined in base.yaml, not the raw motor
// mounting direction. Each motor reading must be multiplied by the corresponding sign in directionMotor_* so later
// control logic sees q/dq/tau_est as joint values in the model coordinate system.
void RL_Real::GetState(RobotState<float> *state)
{
    // yesenceIMU_ is updated asynchronously by OdomCallBack(). Sample the cached value once per control cycle here
    // for FSM and policy observations.
    state->imu.quaternion[0] = this->yesenceIMU_.orientation.w; // w
    state->imu.quaternion[1] = this->yesenceIMU_.orientation.x; // x
    state->imu.quaternion[2] = this->yesenceIMU_.orientation.y; // y
    state->imu.quaternion[3] = this->yesenceIMU_.orientation.z; // z
    state->imu.gyroscope[0] = this->yesenceIMU_.angular_velocity.x;
    state->imu.gyroscope[1] = this->yesenceIMU_.angular_velocity.y;
    state->imu.gyroscope[2] = this->yesenceIMU_.angular_velocity.z;

    // Read CAN1/front-leg motors. CAN1_MAP maps controller array indices to physical CAN ids;
    // directionMotor_Front converts the motor coordinate system to the controller joint coordinate system.
    for (int i = 0; i < 6; ++i) {
        int read_id = CAN1_MAP[i];
        state->motor_state.q[i] =this->motorsInterface->getMotor(read_id)->Get_Position() * directionMotor_Front[i];
        state->motor_state.dq[i]=this->motorsInterface->getMotor(read_id)->Get_Velocity() * directionMotor_Front[i];
        state->motor_state.tau_est[i]=this->motorsInterface->getMotor(read_id)->Get_tau() * directionMotor_Front[i];
    }

    // Read CAN2/rear-leg motors and write indices 6..11 of the 12-DoF vector. The controller always sees
    // one continuous joint vector: FL, FR, RL, RR.
    for (int i = 0; i < 6; ++i) {
        int i_cout   = i + 6;
        int read_id = CAN2_MAP[i];
        state->motor_state.q[i_cout] =this->motorsInterface2->getMotor(read_id)->Get_Position() * directionMotor_Back[i];
        state->motor_state.dq[i_cout]=this->motorsInterface2->getMotor(read_id)->Get_Velocity() * directionMotor_Back[i];
        state->motor_state.tau_est[i_cout]=this->motorsInterface2->getMotor(read_id)->Get_tau() * directionMotor_Back[i];
    }
    #if defined(USE_ROS1)
        std_msgs::Float64MultiArray time_msg;
        std_msgs::Float64MultiArray time_msg2;
    #elif defined(USE_ROS2)
        std_msgs::msg::Float64MultiArray time_msg;
        std_msgs::msg::Float64MultiArray time_msg2;
    #endif
    time_msg.data.resize(6);
    time_msg2.data.resize(6);
    for (size_t i = 0; i < 6; ++i)
    {
        time_msg.data[i] = motorsInterface->getMotor(i+1)->getTimeInterval();
    }
    for (size_t i = 0; i < 6; ++i)
    {
        time_msg2.data[i] = motorsInterface2->getMotor(i+1)->getTimeInterval();
    }

    // The print statements kept below are useful for temporary real-robot bring-up. They print joint positions after
    // directionMotor_* multiplication, which is the q actually seen by the controller and FSM.
    // std::cerr<<"time_interval:   "<<time_msg.data[0]
    //         <<"  time_interval(s): "<<time_msg2.data[0]<<std::endl;
    // std::cerr<<"pos1: "<<state->motor_state.q[0]<<
    //     "     pos2: "<<state->motor_state.q[1]<<
    //     "     pos3: "<<state->motor_state.q[2]<<
    //     "     pos4: "<<state->motor_state.q[3]<<
    //     "     pos5: "<<state->motor_state.q[4]<<
    //     "     pos6: "<<state->motor_state.q[5]<<std::endl;
    // std::cerr<<"pos1: "<<state->motor_state.q[6]<<
    //     "     pos2: "<<state->motor_state.q[7]<<
    //     "     pos3: "<<state->motor_state.q[8]<<
    //     "     pos4: "<<state->motor_state.q[9]<<
    //     "     pos5: "<<state->motor_state.q[10]<<
    //     "     pos6: "<<state->motor_state.q[11]<<std::endl;
    // std::cerr<<"w2: "<<state->imu.quaternion[0]<<"  "
    //     <<"x2: "<<state->imu.quaternion[1]<<"  "
    //     <<"y2: "<<state->imu.quaternion[2]<<"  "
    //     <<"z2: "<<state->imu.quaternion[3]<<"  "<<std::endl;
    // std::cerr<<"x2: "<<state->imu.gyroscope[0]<<"  "
    //         <<"y2: "<<state->imu.gyroscope[1]<<"  "
    //         <<"z2: "<<state->imu.gyroscope[2]<<"  "<<std::endl;
}

// Send controller commands to the two Damiao CAN buses.
//
// RobotCommand is expressed in the controller/model coordinate system. Before sending to motors, convert according to motor mounting
// direction by multiplying back with directionMotor_*, matching the direction conversion in GetState().
// The command source is determined by the current FSM state; it may be fixed-position control or policy output.
void RL_Real::SetCommand(const RobotCommand<float> *command)
{
    // Cache the full 12-DoF command first, then send it to CAN1/CAN2 separately. This keeps bus
    // send logic simple and makes it easier to add target q/kp/kd debug prints later.
    for (int i = 0; i < this->params.Get<int>("num_of_dofs"); ++i)
    {
       rl_date[i].pos_des_ = command->motor_command.q[i];
       rl_date[i].vel_des_ = command->motor_command.dq[i];
       rl_date[i].ff_ = command->motor_command.tau[i];
       rl_date[i].kp_ = command->motor_command.kp[i];
       rl_date[i].kd_ = command->motor_command.kd[i];
    //    std::cerr<<"pos: "<<i<<" "<<rl_date[i].pos_des_<<std::endl;
    }

    // Send CAN1/front-leg commands. The q/dq/tau signs finally sent to motors must match the actual motor
    // mounting direction, not the model coordinate signs.
    for (int i = 0; i < 6; ++i) {
        int rl_idx = CAN1_MAP[i];
        dmSendcmd_[rl_idx].pos_des_ = rl_date[i].pos_des_ * directionMotor_Front[i];
        dmSendcmd_[rl_idx].vel_des_ = rl_date[i].vel_des_ * directionMotor_Front[i];
        dmSendcmd_[rl_idx].ff_ = rl_date[i].ff_ * directionMotor_Front[i];
        dmSendcmd_[rl_idx].kp_ = rl_date[i].kp_;
        dmSendcmd_[rl_idx].kd_ = rl_date[i].kd_;
        this->motorsInterface->control_mit(*this->motorsInterface->getMotor(rl_idx),dmSendcmd_[rl_idx].kp_,dmSendcmd_[rl_idx].kd_ ,
                                            dmSendcmd_[rl_idx].pos_des_,dmSendcmd_[rl_idx].vel_des_, dmSendcmd_[rl_idx].ff_);
        // this->motorsInterface->control_mit(*this->motorsInterface->getMotor(rl_idx), 0.0, 0.0, 0.0, 0.0, 0.0);
    }

    // Send CAN2/rear-leg commands. i_cout converts the local index on the second 6-motor bus into
    // the global index in the 12-DoF command vector.
    for (int i = 0; i < 6; ++i) {
        int i_cout   = i + 6;
        int rl_idx = CAN2_MAP[i];
        dmSendcmd2_[rl_idx].pos_des_ = rl_date[i_cout].pos_des_ * directionMotor_Back[i];
        dmSendcmd2_[rl_idx].vel_des_ = rl_date[i_cout].vel_des_ * directionMotor_Back[i];
        dmSendcmd2_[rl_idx].ff_ = rl_date[i_cout].ff_ * directionMotor_Back[i];
        dmSendcmd2_[rl_idx].kp_ = rl_date[i_cout].kp_;
        dmSendcmd2_[rl_idx].kd_ = rl_date[i_cout].kd_;
        this->motorsInterface2->control_mit(*this->motorsInterface2->getMotor(rl_idx),dmSendcmd2_[rl_idx].kp_,dmSendcmd2_[rl_idx].kd_ ,
                                            dmSendcmd2_[rl_idx].pos_des_,dmSendcmd2_[rl_idx].vel_des_, dmSendcmd2_[rl_idx].ff_);
        // this->motorsInterface2->control_mit(*this->motorsInterface2->getMotor(rl_idx), 0.0, 0.0, 0.0, 0.0, 0.0);
    }
}

// Open the Linux joystick device and record the raw stick value range.
//
// If no gamepad is detected, the node does not exit immediately. This still allows keyboard
// or ROS-side commands during bench testing.
void RL_Real::SetupSysJoystick(const std::string& device, int bits)
{
    this->sys_js = std::make_unique<Joystick>(device);
    if (!this->sys_js->isFound())
    {
        std::cout << LOGGER::ERROR << "Joystick [" << device << "] open failed." << std::endl;
        // exit(1);
    }
    this->sys_js_max_value = (1 << (bits - 1));
}

// Poll all pending gamepad events and convert them to controller inputs.
//
// Button::on_press is edge-triggered: it is true only in the polling cycle where the button changes
// from released to pressed. The main control loop clears these one-shot inputs after running the FSM, so pressing A once
// requests one state transition and does not retrigger in later cycles.
void RL_Real::GetSysJoystick()
{
    // Before reading new events, clear one-shot press/release events from the previous poll.
    for (int i = 0; i < 20; ++i)
    {
        this->sys_js_button[i].on_press = false;
        this->sys_js_button[i].on_release = false;
    }
    // Return directly if the gamepad is not open to avoid null pointer access.
    if (!this->sys_js) {return;}
    if (this->DogUsbShouldBlockFallback()) {return;}
    while (this->sys_js->sample(&this->sys_js_event))
    {
        if (this->sys_js_event.isButton())
        {
            this->sys_js_button[this->sys_js_event.number].update(this->sys_js_event.value);
        }
        else if (this->sys_js_event.isAxis())
        {
            double normalized = double(this->sys_js_event.value) / this->sys_js_max_value;
            if (std::abs(normalized) < this->axis_deadzone)
            {
                this->sys_js_axis[this->sys_js_event.number] = 0;
            }
            else
            {
                this->sys_js_axis[this->sys_js_event.number] = this->sys_js_event.value;
            }
        }
    }

    // Map physical buttons into unified Gamepad enums. The FSM only cares about these abstract inputs
    // and does not depend directly on raw Linux joystick button numbers.
    if (this->sys_js_button[0].on_press) this->control.SetGamepad(Input::Gamepad::A);
    if (this->sys_js_button[1].on_press) this->control.SetGamepad(Input::Gamepad::B);
    if (this->sys_js_button[2].on_press) this->control.SetGamepad(Input::Gamepad::X);
    if (this->sys_js_button[3].on_press) this->control.SetGamepad(Input::Gamepad::Y);
    if (this->sys_js_button[4].on_press) this->control.SetGamepad(Input::Gamepad::LB);
    if (this->sys_js_button[5].on_press) this->control.SetGamepad(Input::Gamepad::RB);
    if (this->sys_js_button[9].on_press) this->control.SetGamepad(Input::Gamepad::LStick);
    if (this->sys_js_button[10].on_press) this->control.SetGamepad(Input::Gamepad::RStick);
    if (this->sys_js_axis[7] < 0) this->control.SetGamepad(Input::Gamepad::DPadUp);
    if (this->sys_js_axis[7] > 0) this->control.SetGamepad(Input::Gamepad::DPadDown);
    if (this->sys_js_axis[6] > 0) this->control.SetGamepad(Input::Gamepad::DPadLeft);
    if (this->sys_js_axis[6] < 0) this->control.SetGamepad(Input::Gamepad::DPadRight);
    if (this->sys_js_button[4].pressed && this->sys_js_button[0].on_press) this->control.SetGamepad(Input::Gamepad::LB_A);
    if (this->sys_js_button[4].pressed && this->sys_js_button[1].on_press) this->control.SetGamepad(Input::Gamepad::LB_B);
    if (this->sys_js_button[4].pressed && this->sys_js_button[2].on_press) this->control.SetGamepad(Input::Gamepad::LB_X);
    if (this->sys_js_button[4].pressed && this->sys_js_button[3].on_press) this->control.SetGamepad(Input::Gamepad::LB_Y);
    if (this->sys_js_button[4].pressed && this->sys_js_button[9].on_press) this->control.SetGamepad(Input::Gamepad::LB_LStick);
    if (this->sys_js_button[4].pressed && this->sys_js_button[10].on_press) this->control.SetGamepad(Input::Gamepad::LB_RStick);
    if (this->sys_js_button[4].pressed && this->sys_js_axis[7] < 0) this->control.SetGamepad(Input::Gamepad::LB_DPadUp);
    if (this->sys_js_button[4].pressed && this->sys_js_axis[7] > 0) this->control.SetGamepad(Input::Gamepad::LB_DPadDown);
    if (this->sys_js_button[4].pressed && this->sys_js_axis[6] > 0) this->control.SetGamepad(Input::Gamepad::LB_DPadRight);
    if (this->sys_js_button[4].pressed && this->sys_js_axis[6] < 0) this->control.SetGamepad(Input::Gamepad::LB_DPadLeft);
    if (this->sys_js_button[5].pressed && this->sys_js_button[0].on_press) this->control.SetGamepad(Input::Gamepad::RB_A);
    if (this->sys_js_button[5].pressed && this->sys_js_button[1].on_press) this->control.SetGamepad(Input::Gamepad::RB_B);
    if (this->sys_js_button[5].pressed && this->sys_js_button[2].on_press) this->control.SetGamepad(Input::Gamepad::RB_X);
    if (this->sys_js_button[5].pressed && this->sys_js_button[3].on_press) this->control.SetGamepad(Input::Gamepad::RB_Y);
    if (this->sys_js_button[5].pressed && this->sys_js_button[9].on_press) this->control.SetGamepad(Input::Gamepad::RB_LStick);
    if (this->sys_js_button[5].pressed && this->sys_js_button[10].on_press) this->control.SetGamepad(Input::Gamepad::RB_RStick);
    if (this->sys_js_button[5].pressed && this->sys_js_axis[7] < 0) this->control.SetGamepad(Input::Gamepad::RB_DPadUp);
    if (this->sys_js_button[5].pressed && this->sys_js_axis[7] > 0) this->control.SetGamepad(Input::Gamepad::RB_DPadDown);
    if (this->sys_js_button[5].pressed && this->sys_js_axis[6] > 0) this->control.SetGamepad(Input::Gamepad::RB_DPadRight);
    if (this->sys_js_button[5].pressed && this->sys_js_axis[6] < 0) this->control.SetGamepad(Input::Gamepad::RB_DPadLeft);
    if (this->sys_js_button[4].pressed && this->sys_js_button[5].on_press) this->control.SetGamepad(Input::Gamepad::LB_RB);

    // Stick axis values are converted into desired base velocity commands. Each state can decide whether to use
    // control.x, control.y, and control.yaw.
    float ly = -float(this->sys_js_axis[1]) / float(this->sys_js_max_value);
    float lx = -float(this->sys_js_axis[0]) / float(this->sys_js_max_value);
    float rx = -float(this->sys_js_axis[3]) / float(this->sys_js_max_value);

    bool has_input = (ly != 0.0f || lx != 0.0f || rx != 0.0f);
    if (has_input)
    {
        // Shape joystick axes into the deploy command envelope before use.
        const rl_command::PlanarCommand planar = rl_command::ShapePlanarCommand(ly, lx);
        this->control.x = planar.x;
        this->control.y = planar.y;
        this->control.yaw = rl_command::ShapeYawCommand(rx);
        this->raw_command_inputs_ = {ly, lx, rx};
        this->command_input_source_ = "joystick_axes";
        this->sys_js_active = true;
    }
    else if (this->sys_js_active)
    {
        this->control.x = 0.0f;
        this->control.y = 0.0f;
        this->control.yaw = 0.0f;
        this->sys_js_active = false;
        this->raw_command_inputs_.assign(3, 0.0f);
    }
}

// Run one real-time control cycle.
//
// This is the core closed-loop path for the real robot:
//   1. GetState() reads IMU and motor feedback.
//   2. StateController() lets the FSM generate the next RobotCommand from the current state.
//   3. ClearInput() clears one-shot buttons so the same press is not consumed repeatedly.
//   4. SetCommand() converts RobotCommand into CAN MIT commands and sends them to motors.
bool RL_Real::DogUsbShouldBlockFallback() const
{
    if (!this->dog_usb_enable || !this->dog_usb_receiver)
    {
        return false;
    }

    const DogUsbState state = this->dog_usb_receiver->GetLatestState();
    if (!state.valid)
    {
        return false;
    }

    const auto now = std::chrono::steady_clock::now();
    const bool usb_fresh =
        this->dog_usb_receiver->IsConnected() &&
        (now - state.last_valid_frame_time <= std::chrono::milliseconds(this->dog_usb_timeout_ms));

    if (!this->dog_usb_allow_fallback)
    {
        return true;
    }
    return usb_fresh;
}

void RL_Real::TriggerDogUsbGamepad(Input::Gamepad gamepad, const char* name)
{
    this->control.SetGamepad(gamepad);
    std::cout << LOGGER::INFO << "[dog_usb] event " << name << std::endl;
}

void RL_Real::RequestDogUsbExit(const char* reason)
{
    if (this->dog_usb_exit_requested)
    {
        return;
    }

    this->dog_usb_exit_requested = true;
    this->dog_usb_exit_shutdown_after_command = false;
    this->dog_usb_exit_started_at = std::chrono::steady_clock::now();
    this->control.x = 0.0f;
    this->control.y = 0.0f;
    this->control.yaw = 0.0f;
    this->ResetCommandSmoothing();

    std::cout << LOGGER::WARNING << "[dog_usb] " << reason
              << "; requesting getdown then rl_real_d1 shutdown" << std::endl;
}

std::string RL_Real::CurrentFsmStateName() const
{
    if (!this->fsm.current_state_)
    {
        return "";
    }
    return this->fsm.current_state_->GetStateName();
}

bool RL_Real::DogUsbExitTimedOut() const
{
    if (!this->dog_usb_exit_requested)
    {
        return false;
    }

    const auto elapsed = std::chrono::steady_clock::now() - this->dog_usb_exit_started_at;
    return elapsed >= std::chrono::milliseconds(this->dog_usb_l1_exit_timeout_ms);
}

void RL_Real::HoldDogUsbExitInputs()
{
    if (!this->dog_usb_exit_requested)
    {
        return;
    }

    this->control.x = 0.0f;
    this->control.y = 0.0f;
    this->control.yaw = 0.0f;
    this->control.current_keyboard = Input::Keyboard::None;
    this->control.last_keyboard = Input::Keyboard::None;
    this->control.current_gamepad = Input::Gamepad::None;
    this->ResetCommandSmoothing();

    const std::string state_name = this->CurrentFsmStateName();
    if (state_name == "RLFSMStateGetUp" || state_name == "RLFSMStateRLLocomotion")
    {
        this->control.SetGamepad(Input::Gamepad::B);
    }
}

void RL_Real::UpdateDogUsbExitShutdown()
{
    if (!this->dog_usb_exit_requested)
    {
        return;
    }

    this->control.x = 0.0f;
    this->control.y = 0.0f;
    this->control.yaw = 0.0f;
    this->ResetCommandSmoothing();

    const std::string state_name = this->CurrentFsmStateName();
    if (state_name == "RLFSMStatePassive")
    {
        this->dog_usb_exit_shutdown_after_command = true;
        std::cout << LOGGER::INFO
                  << "[dog_usb] L1 OFF exit reached passive; shutting down after this command"
                  << std::endl;
        return;
    }

    if (this->DogUsbExitTimedOut())
    {
        this->dog_usb_exit_shutdown_after_command = true;
        std::cout << LOGGER::WARNING
                  << "[dog_usb] L1 OFF exit timeout in state " << state_name
                  << "; forcing rl_real_d1 shutdown" << std::endl;
    }
}

void RL_Real::ShutdownDogUsbExitIfReady()
{
    if (!this->dog_usb_exit_shutdown_after_command)
    {
        return;
    }

    this->dog_usb_exit_shutdown_after_command = false;

#if defined(USE_ROS1)
    ros::shutdown();
#elif defined(USE_ROS2)
    if (rclcpp::ok())
    {
        rclcpp::shutdown();
    }
#endif
}

void RL_Real::LogDogUsbStatus(bool safe_state, bool usb_timeout, bool remote_timeout, bool serial_connected)
{
    if (!this->dog_usb_status_initialized || this->dog_usb_last_safe_state != safe_state)
    {
        std::cout << (safe_state ? LOGGER::WARNING : LOGGER::INFO)
                  << "[dog_usb] safe_state=" << (safe_state ? "ON" : "OFF") << std::endl;
    }
    if (!this->dog_usb_status_initialized || this->dog_usb_last_usb_timeout != usb_timeout)
    {
        std::cout << (usb_timeout ? LOGGER::WARNING : LOGGER::INFO)
                  << "[dog_usb] usb_timeout=" << (usb_timeout ? "ON" : "OFF") << std::endl;
    }
    if (!this->dog_usb_status_initialized || this->dog_usb_last_remote_timeout != remote_timeout)
    {
        std::cout << (remote_timeout ? LOGGER::WARNING : LOGGER::INFO)
                  << "[dog_usb] remote_timeout=" << (remote_timeout ? "ON" : "OFF") << std::endl;
    }
    if (!this->dog_usb_status_initialized || this->dog_usb_last_serial_connected != serial_connected)
    {
        std::cout << (serial_connected ? LOGGER::INFO : LOGGER::WARNING)
                  << "[dog_usb] serial_connected=" << (serial_connected ? "ON" : "OFF") << std::endl;
    }

    this->dog_usb_status_initialized = true;
    this->dog_usb_last_safe_state = safe_state;
    this->dog_usb_last_usb_timeout = usb_timeout;
    this->dog_usb_last_remote_timeout = remote_timeout;
    this->dog_usb_last_serial_connected = serial_connected;
}

void RL_Real::ResetCommandSmoothing()
{
    this->command_smoothing_reset_requested_ = true;
}

std::vector<float> RL_Real::SmoothCommands(const std::vector<float>& target_commands, float dt)
{
    return rl_command::SmoothCommands(
        target_commands, dt, this->smoothed_commands_,
        this->command_smoothing_initialized_, this->command_smoothing_reset_requested_);
}

void RL_Real::ApplyDogUsbControl(bool emit_events)
{
    if (this->dog_usb_exit_requested)
    {
        this->control.x = 0.0f;
        this->control.y = 0.0f;
        this->control.yaw = 0.0f;
        this->ResetCommandSmoothing();
        return;
    }

    if (!this->dog_usb_enable || !this->dog_usb_receiver)
    {
        return;
    }

    const DogUsbState state = this->dog_usb_receiver->GetLatestState();
    if (!state.valid)
    {
        return;
    }

    this->dog_usb_has_taken_control = true;

    const auto now = std::chrono::steady_clock::now();
    const bool serial_connected = this->dog_usb_receiver->IsConnected();
    const bool usb_fresh =
        serial_connected &&
        (now - state.last_valid_frame_time <= std::chrono::milliseconds(this->dog_usb_timeout_ms));
    const bool remote_fresh =
        state.last_remote_age_ms <= static_cast<uint32_t>(this->dog_remote_timeout_ms);
    const bool dog_safe = state.safe_state;
    const bool usb_timeout = !usb_fresh;
    const bool remote_timeout = !remote_fresh;
    const bool channel_owns = !this->dog_usb_allow_fallback || usb_fresh;
    const bool dog_control_valid = channel_owns && usb_fresh && remote_fresh && !dog_safe;

    if (emit_events)
    {
        this->LogDogUsbStatus(dog_safe, usb_timeout, remote_timeout, serial_connected);
        if (channel_owns)
        {
            this->control.current_keyboard = Input::Keyboard::None;
            this->control.last_keyboard = Input::Keyboard::None;
            this->control.current_gamepad = Input::Gamepad::None;
        }
    }

    if (dog_control_valid)
    {
        const rl_command::PlanarCommand planar = rl_command::ShapePlanarCommand(static_cast<float>(state.x), static_cast<float>(state.y));
        this->control.x = planar.x;
        this->control.y = planar.y;
        this->control.yaw = rl_command::ShapeYawCommand(static_cast<float>(state.yaw));
        this->raw_command_inputs_ = {static_cast<float>(state.x), static_cast<float>(state.y), static_cast<float>(state.yaw)};
        this->command_input_source_ = "dog_usb_axes";
    }
    else if (channel_owns || dog_safe || remote_timeout || !serial_connected)
    {
        this->control.x = 0.0f;
        this->control.y = 0.0f;
        this->control.yaw = 0.0f;
        this->ResetCommandSmoothing();
        this->raw_command_inputs_.assign(3, 0.0f);
    }

    if (!emit_events || !usb_fresh)
    {
        return;
    }

    const uint16_t kBtnSwL1 = static_cast<uint16_t>(1u << this->dog_usb_l1_button_bit);
    constexpr uint16_t kBtnSwL2 = 1u << 9;
    constexpr uint16_t kBtnSwR1 = 1u << 10;
    constexpr uint16_t kBtnSwR2 = 1u << 11;

    const uint16_t buttons = state.buttons;
    const uint16_t prev_buttons = this->dog_usb_prev_buttons;

    if (this->dog_usb_l1_off_exit)
    {
        const bool l1_now = (buttons & kBtnSwL1) != 0;
        const bool l1_prev = (prev_buttons & kBtnSwL1) != 0;
        if (l1_now)
        {
            if (!this->dog_usb_l1_seen_on)
            {
                std::cout << LOGGER::INFO
                          << "[dog_usb] L1 ON armed for OFF exit, buttons=0x"
                          << std::hex << buttons << std::dec
                          << " remote_age_ms=" << state.last_remote_age_ms
                          << std::endl;
            }
            this->dog_usb_l1_seen_on = true;
        }
        else if (this->dog_usb_l1_seen_on && l1_prev)
        {
            std::cout << LOGGER::WARNING
                      << "[dog_usb] L1 OFF edge detected, buttons=0x"
                      << std::hex << buttons
                      << " prev=0x" << prev_buttons << std::dec
                      << " remote_age_ms=" << state.last_remote_age_ms
                      << std::endl;
            this->RequestDogUsbExit("L1_OFF_Exit");
        }
    }

    if (dog_control_valid)
    {
        const bool r1_now = (buttons & kBtnSwR1) != 0;
        const bool r1_prev = (prev_buttons & kBtnSwR1) != 0;
        if (r1_now && !r1_prev)
        {
            this->TriggerDogUsbGamepad(Input::Gamepad::A, "R1_ON_GetUp");
        }
        else if (!r1_now && r1_prev)
        {
            this->TriggerDogUsbGamepad(Input::Gamepad::B, "R1_OFF_GetDown");
        }

        const bool l2_now = (buttons & kBtnSwL2) != 0;
        const bool l2_prev = (prev_buttons & kBtnSwL2) != 0;
        if (l2_now && !l2_prev)
        {
            this->TriggerDogUsbGamepad(Input::Gamepad::LB_X, "L2_ON_Passive");
        }

        const bool r2_now = (buttons & kBtnSwR2) != 0;
        const bool r2_prev = (prev_buttons & kBtnSwR2) != 0;
        if (r2_now && !r2_prev)
        {
            this->TriggerDogUsbGamepad(Input::Gamepad::RB_DPadUp, "R2_ON_RLLocomotion");
        }
    }

    this->dog_usb_prev_buttons = buttons;
}

void RL_Real::RobotControl()
{
    this->GetState(&this->robot_state);
    this->ApplyDogUsbControl(true);
    this->HoldDogUsbExitInputs();
    this->StateController(&this->robot_state, &this->robot_command);
    this->ApplyDogUsbControl(false);
    this->UpdateDogUsbExitShutdown();
    this->control.ClearInput();
    this->SetCommand(&this->robot_command);
    this->ShutdownDogUsbExitIfReady();

    // joint_state_msg_.header.stamp = this->now();
    // joint_state_msg_.name = joint_names_;
    // joint_state_msg_.position.resize(12);
    // joint_state_msg_.velocity.resize(12);
    // for (int i = 0; i < 12; ++i)
    // {
    //     joint_state_msg_.position[i] = robot_state.motor_state.q[i];
    //     joint_state_msg_.velocity[i] = robot_command.motor_command.q[i];
    // }
    // joint_state_pub_->publish(joint_state_msg_);
}

// Run the neural-network policy inference loop.
//
// This loop is separate from the 200 Hz motor control loop. RunModel() only performs inference after the relevant FSM state
// finishes policy initialization and sets rl_init_done to true.
void RL_Real::RunModel()
{
    if (this->rl_init_done)
    {
        this->episode_length_buf += 1;
        this->obs.ang_vel = this->robot_state.imu.gyroscope;
        this->ApplyDogUsbControl(false);
        std::vector<float> target_commands = {this->control.x, this->control.y, this->control.yaw};
        std::vector<float> raw_trace = this->raw_command_inputs_;
        std::string trace_source = this->command_input_source_;
        std::string raw_units = trace_source.find("axes") != std::string::npos ? "normalized_axis" : "mps_radps";
        if (trace_source == "control")
        {
            raw_trace = target_commands;
        }
#if !defined(USE_CMAKE)
        if (this->control.navigation_mode)
        {
            target_commands = {(float)this->cmd_vel.linear.x, (float)this->cmd_vel.linear.y, (float)this->cmd_vel.angular.z};
            raw_trace = target_commands;
            trace_source = "cmd_vel";
            raw_units = "mps_radps";
        }
#endif
        // Final safety net for keyboard/nav/abnormal command sources.
        // Normal joystick and DOG_CTRL inputs are shaped before this point.
        target_commands = rl_command::ClampCommands(target_commands);
        const float command_dt = std::max(
            this->params.Get<float>("dt") * static_cast<float>(this->params.Get<int>("decimation")),
            1.0e-4f);
        this->obs.commands = this->SmoothCommands(target_commands, command_dt);
        rl_command::LogCommandTrace(trace_source, raw_units, raw_trace, target_commands, this->obs.commands);
        this->obs.base_quat = this->robot_state.imu.quaternion;
        this->obs.dof_pos = this->robot_state.motor_state.q;
        this->obs.dof_vel = this->robot_state.motor_state.dq;

        // Forward() returns the raw policy-network action. ComputeOutput() then uses
        // parameters such as action_scale, default_dof_pos, and rl_kp/rl_kd from config.yaml
        // to convert it into target joint positions, target joint velocities, and estimated torque.
        this->obs.actions = this->Forward();
        this->ComputeOutput(this->obs.actions, this->output_dof_pos, this->output_dof_vel, this->output_dof_tau);

        if (!this->output_dof_pos.empty())
        {
            output_dof_pos_queue.push(this->output_dof_pos);
        }
        if (!this->output_dof_vel.empty())
        {
            output_dof_vel_queue.push(this->output_dof_vel);
        }
        if (!this->output_dof_tau.empty())
        {
            output_dof_tau_queue.push(this->output_dof_tau);
        }

#ifdef CSV_LOGGER
        std::vector<float> tau_est = this->robot_state.motor_state.tau_est;
        this->CSVLogger(this->output_dof_tau, tau_est, this->obs.dof_pos, this->output_dof_pos, this->obs.dof_vel);
#endif
    }
}

// Run forward inference for the currently loaded policy model.
//
// A deployed policy may need only the current observation or a history of observations; this is determined by
// config.yaml/observations_history. model_mutex avoids concurrent access to the same model object between inference
// and model reinitialization.
std::vector<float> RL_Real::Forward()
{
    std::unique_lock<std::mutex> lock(this->model_mutex, std::try_to_lock);

    // If the model is being reinitialized, do not block the control thread this cycle; reuse the previous action.
    if (!lock.owns_lock())
    {
        std::cout << LOGGER::WARNING << "Model is being reinitialized, using previous actions" << std::endl;
        return this->obs.actions;
    }

    std::vector<float> clamped_obs = this->ComputeObservation();

    std::vector<float> actions;
    if (!this->params.Get<std::vector<int>>("observations_history").empty())
    {
        // HIMLoco-style policies use short observation histories so the model can infer velocity and latent dynamics
        // from the latest robot responses.
        this->history_obs_buf.insert(clamped_obs);
        this->history_obs = this->history_obs_buf.get_obs_vec(this->params.Get<std::vector<int>>("observations_history"));
        actions = this->model->forward({this->history_obs});
    }
    else
    {
        actions = this->model->forward({clamped_obs});
    }

    if (!this->params.Get<std::vector<float>>("clip_actions_upper").empty() && !this->params.Get<std::vector<float>>("clip_actions_lower").empty())
    {
        return clamp(actions, this->params.Get<std::vector<float>>("clip_actions_lower"), this->params.Get<std::vector<float>>("clip_actions_upper"));
    }
    else
    {
        return actions;
    }
}

// Update the optional joint plot window.
//
// This logic is compiled only when the PLOT macro is defined. matplotlib calls are unsuitable for real-time control,
// so keep it disabled during normal real-robot operation.
void RL_Real::Plot()
{
    this->plot_t.erase(this->plot_t.begin());
    this->plot_t.push_back(this->motiontime);
    plt::cla();
    plt::clf();
    for (int i = 0; i < this->params.Get<int>("num_of_dofs"); ++i)
    {
        this->plot_real_joint_pos[i].erase(this->plot_real_joint_pos[i].begin());
        this->plot_target_joint_pos[i].erase(this->plot_target_joint_pos[i].begin());
        // this->plot_real_joint_pos[i].push_back(this->unitree_low_state.motorState[i].q);
        // this->plot_target_joint_pos[i].push_back(this->unitree_low_command.motorCmd[i].q);
        plt::subplot(this->params.Get<int>("num_of_dofs"), 1, i + 1);
        plt::named_plot("_real_joint_pos", this->plot_t, this->plot_real_joint_pos[i], "r");
        plt::named_plot("_target_joint_pos", this->plot_t, this->plot_target_joint_pos[i], "b");
        plt::xlim(this->plot_t.front(), this->plot_t.back());
    }
    // plt::legend();
    plt::pause(0.0001);
}

// Initialize fixed covariance values in the cached IMU data structure.
bool RL_Real::setupImu() {
  this->imuData_.ori_cov[0] = 0.0012;
  this->imuData_.ori_cov[4] = 0.0012;
  this->imuData_.ori_cov[8] = 0.0012;
  this->imuData_.angular_vel_cov[0] = 0.0004;
  this->imuData_.angular_vel_cov[4] = 0.0004;
  this->imuData_.angular_vel_cov[8] = 0.0004;
  return true;
}
#if !defined(USE_CMAKE)

// Cache the latest navigation velocity command.
//
// This command is used by RunModel() only when navigation_mode is enabled. Gamepad input
// and other FSM states do not depend directly on this callback.
void RL_Real::CmdvelCallback(
#if defined(USE_ROS1)
    const geometry_msgs::Twist::ConstPtr &msg
#elif defined(USE_ROS2)
    const geometry_msgs::msg::Twist::SharedPtr msg
#endif
)
{
    this->cmd_vel = *msg;
}
#endif

#if defined(USE_ROS1)

// Handle Ctrl-C in ROS1 builds and trigger ros::shutdown().
void sigintHandler(int)
{
  ros::shutdown();
    exit(0);
}
#endif

// Program entry point shared by ROS1, ROS2, and non-ROS builds.
int main(int argc, char **argv)
{
#if defined(USE_ROS1)
    signal(SIGINT, sigintHandler);
    ros::init(argc, argv, "rl_sar");
    RL_Real rl_sar(argc, argv);
    ros::spin();
#elif defined(USE_ROS2)
    rclcpp::init(argc, argv);
    auto rl_sar = std::make_shared<RL_Real>(argc, argv);
    rclcpp::spin(rl_sar->ros2_node);
    rclcpp::shutdown();
    return 0;
#else
    RL_Real rl_sar(argc, argv);
    while (true) {sleep(10);}
    return 0;
#endif
}
